### PR TITLE
registry can resolve an already closed challenge

### PR DESCRIPTION
**Pull request by ewilz**

### CODE REVIEW

**Comment by mikec** [comment]
@emaG3m awesome! I think there's one other bug .. can `resolveChallenge()` be called more than once now? should add a check for that and test coverage if that's the case

**Comment by ewilz** [comment]
in both pass/fail cases we test that resolving deletes the challenge. Then there's another test to make sure resolveChallenge() reverts if there's not existing challenge. I figured this covered things and didn't right a specific test about calling it twice

**Comment by mikec** [comment]
oh yah that's true! no need to add anything extra then.

**Comment by mikec** [comment]
niiiice 👍 👍

**Pull request merged**
